import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  TextInput,
  Alert,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import { collection, getDocs, addDoc, query, where, deleteDoc, doc } from 'firebase/firestore';
import { db, auth } from '../backend/firebase/config';

export default function ShoppingListScreen() {
  const [items, setItems] = useState<any[]>([]);
  const [newItem, setNewItem] = useState('');
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    fetchShoppingList();
  }, []);

  const fetchShoppingList = async () => {
    try {
      const q = query(collection(db, 'shoppingList'));
      const querySnapshot = await getDocs(q);
      const list: any[] = [];
      querySnapshot.forEach((doc) => {
        list.push({ id: doc.id, ...doc.data() });
      });
      setItems(list);
    } catch (error) {
      console.error("Error fetching shopping list:", error);
    }
  };

  const addItem = async () => {
    if (!newItem.trim()) return;
    try {
      await addDoc(collection(db, 'shoppingList'), {
        name: newItem,
        checked: false,
        createdAt: new Date()
      });
      setNewItem('');
      fetchShoppingList();
    } catch (error) {
      Alert.alert('Error', 'Failed to add item');
    }
  };

  const toggleItem = async (id: string, currentStatus: boolean) => {
    // For simplicity in this demo, we just delete or visual toggle
    // In a real app, you'd update the 'checked' field in Firestore
    setItems(items.map(item => item.id === id ? { ...item, checked: !currentStatus } : item));
  };

  const deleteItem = async (id: string) => {
    try {
      await deleteDoc(doc(db, 'shoppingList', id));
      fetchShoppingList();
    } catch (error) {
      Alert.alert('Error', 'Failed to delete item');
    }
  };

  // Market Trend: Auto-suggest items based on low pantry stock
  const autoSuggest = async () => {
    setLoading(true);
    try {
      const pantrySnapshot = await getDocs(collection(db, 'pantry'));
      let suggestedCount = 0;
      for (const pantryDoc of pantrySnapshot.docs) {
        const data = pantryDoc.data();
        if (parseInt(data.stock) <= 1) {
          // Check if already in shopping list
          const exists = items.some(i => i.name.toLowerCase() === data.name.toLowerCase());
          if (!exists) {
            await addDoc(collection(db, 'shoppingList'), {
              name: data.name,
              checked: false,
              autoGenerated: true,
              createdAt: new Date()
            });
            suggestedCount++;
          }
        }
      }
      if (suggestedCount > 0) {
        Alert.alert('AI Smart List', `Added ${suggestedCount} low-stock items to your list!`);
        fetchShoppingList();
      } else {
        Alert.alert('AI Smart List', 'Your pantry stock looks good! Nothing to add.');
      }
    } catch (error) {
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <LinearGradient
      colors={['#0F172A', '#1E293B']}
      style={{ flex: 1 }}
    >
      <View style={styles.container}>
        <View style={styles.header}>
          <Text style={styles.title}>Shopping List</Text>
          <TouchableOpacity style={styles.aiButton} onPress={autoSuggest} disabled={loading}>
            <Ionicons name="sparkles" size={20} color="white" />
            <Text style={styles.aiButtonText}>{loading ? '...' : 'AI Suggest'}</Text>
          </TouchableOpacity>
        </View>

        <View style={styles.inputContainer}>
          <TextInput
            style={styles.input}
            placeholder="Add missing item..."
            placeholderTextColor="#94A3B8"
            value={newItem}
            onChangeText={setNewItem}
          />
          <TouchableOpacity style={styles.addButton} onPress={addItem}>
            <Ionicons name="add" size={28} color="white" />
          </TouchableOpacity>
        </View>

        <ScrollView showsVerticalScrollIndicator={false}>
          {items.map((item) => (
            <View key={item.id} style={styles.itemCard}>
              <TouchableOpacity
                style={styles.itemMain}
                onPress={() => toggleItem(item.id, item.checked)}
              >
                <Ionicons
                  name={item.checked ? "checkbox" : "square-outline"}
                  size={24}
                  color={item.checked ? "#22C55E" : "#94A3B8"}
                />
                <Text style={[
                  styles.itemText,
                  item.checked && styles.completedText
                ]}>
                  {item.name}
                  {item.autoGenerated && <Text style={styles.autoTag}> (AI)</Text>}
                </Text>
              </TouchableOpacity>
              <TouchableOpacity onPress={() => deleteItem(item.id)}>
                <Ionicons name="trash-outline" size={20} color="#EF4444" />
              </TouchableOpacity>
            </View>
          ))}

          {items.length === 0 && (
            <View style={styles.emptyView}>
              <Ionicons name="cart-outline" size={64} color="rgba(255,255,255,0.1)" />
              <Text style={styles.emptyText}>Your list is empty</Text>
            </View>
          )}
        </ScrollView>
      </View>
    </LinearGradient>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, padding: 20, paddingTop: 60 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 25 },
  title: { fontSize: 28, fontWeight: 'bold', color: 'white' },
  aiButton: {
    flexDirection: 'row',
    backgroundColor: '#4F46E5',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    alignItems: 'center'
  },
  aiButtonText: { color: 'white', fontWeight: 'bold', marginLeft: 6, fontSize: 12 },
  inputContainer: {
    flexDirection: 'row',
    marginBottom: 25,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 16,
    padding: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)'
  },
  input: { flex: 1, color: 'white', paddingHorizontal: 15, fontSize: 16 },
  addButton: {
    backgroundColor: '#10B981',
    width: 45,
    height: 45,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center'
  },
  itemCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255,255,255,0.05)',
    padding: 15,
    borderRadius: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)'
  },
  itemMain: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  itemText: { color: 'white', fontSize: 16, marginLeft: 12 },
  completedText: { textDecorationLine: 'line-through', color: '#64748B' },
  autoTag: { fontSize: 10, color: '#4F46E5', fontWeight: 'bold' },
  emptyView: { alignItems: 'center', marginTop: 100 },
  emptyText: { color: '#64748B', fontSize: 16, marginTop: 10 }
});
